name: find_movies
description: "Una aplicación basada en TMDB API para encontrar películas y series."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  flutter_dotenv: ^5.2.1
  go_router: ^16.1.0
  flutter_bloc: ^9.1.1
  either_dart: ^1.0.0
  http: ^1.5.0
  dartz: ^0.10.1
  get_it: ^8.2.0
  injectable: ^2.1.0
  freezed_annotation: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  mockito: ^5.5.0
  build_runner: ^2.4.6
  freezed: ^3.0.0-0.0.dev

flutter:
  uses-material-design: true

  assets:
    - .env
